<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="PREDATOR" failures="1" tests="2" name="runner.Runner_ExtentReporter" time="12.869" errors="0" timestamp="2025-04-27T10:22:43 IST" skipped="0">
  <testcase classname="runner.Runner_ExtentReporter" name="runScenario" time="3.788"/>
  <system-out/>
  <testcase classname="runner.Runner_ExtentReporter" name="runScenario" time="9.081">
    <failure message="expected [Thank you for your order!!] but found [Thank you for your order!]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Thank you for your order!!] but found [Thank you for your order!]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at stepDefinitions.StepDefinitionMapping.the_confirmation_page_should_display_the_message(StepDefinitionMapping.java:85)
at âœ½.the confirmation page should display the message "Thank you for your order!!"(file:///D:/All%20Desktop%20folders/BDD%20Cucumber/Cucumber%20Self%20Practice/SwagLabs/src/test/java/featureFiles/Purchase.feature:15)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
</testsuite> <!-- runner.Runner_ExtentReporter -->
